[envs.compare]
command = "bril2json < {filename} | brili {args} "
output.out = "-"

[envs.briloop]
command = "bril2json < {filename} | ./run.sh | briloop2txt"
output.briloop = "-"

[envs.verify]
command = "bril2json < {filename} | ./run.sh | deno run $BRIL/brili.ts {args}"
output.out = "-"
